### ISSUE TITLE
Bioconda Recipe

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#255]
Bioconda is an environment to build and distribute bioinformatics software. Denovogear needs to have a recipe on bioconda.

https://bioconda.github.io/contribute-a-recipe.html

**Comment by druvus** [comment]
denovogear is included in Bioconda but the recipe is currently "blacklisted" due to some [boost issues](https://github.com/bioconda/bioconda-recipes/blob/master/boost-1.61-migration-blacklist) so it hasn't been rebuilt using current pinnings.

You need to remove denovogear from that file to build an updated recipe.

**Comment by reedacartwright** [comment]
I was unaware that Denovogear had a recipe and it was blacklisted.  The develop branch works with boost 1.61, and I see that [bioconda is trying to build 1.1.1](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/denovogear/meta.yaml). Do you know if bioconda builds packages for stable, but "beta" branches?

**Comment by druvus** [comment]
It is ok to build stable beta releases. You can use specific commit by using an url like this: https://github.com/denovogear/denovogear/archive/fa3a553f6be3cee2e6314e49e0347f124e5f86a5.tar.gz

But it is of course preferable to tag a release.

**Comment by reedacartwright** [comment]
@jgarc111, let's use commit id 95209cc8a32e4bbe274819d1a07ab3f91b1cfa67

**Comment by reedacartwright** [comment]
@jgarc111, can you post the compiler failure you are having with gcc 4.8.2

**Comment by jgarciamesa** [comment]
With gcc 4.8.4 the error message is:
`In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33:0,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/home/ubuntu/denovogear/src/lib/../include/dng/io/file.h: In constructor ‘dng::io::File::File(dng::io::File&&)’:
/home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:98:33: error: use of deleted function ‘std::basic_fstream<char>::basic_fstream(const std::basic_fstream<char>&)’
     file_{std::move(other.file_)}
                                 ^
In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:27:0,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/usr/include/c++/4.8/fstream:776:11: note: ‘std::basic_fstream<char>::basic_fstream(const std::basic_fstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:776:11: error: use of deleted function ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.8/iterator:65:0,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/istream:795:11: note: ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.8/istream:795:11: error: use of deleted function ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’
/usr/include/c++/4.8/istream:58:11: note: ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8/istream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8/ios:42:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/bits/ios_base.h:792:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);
     ^
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8/iterator:65:0,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/istream:795:11: error: use of deleted function ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’
     class basic_iostream
           ^
In file included from /usr/include/c++/4.8/iterator:64:0,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/ostream:58:11: note: ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8/iterator:65:0,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/istream:795:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_iostream
           ^
In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:27:0,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/usr/include/c++/4.8/fstream:776:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:776:11: error: use of deleted function ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’
/usr/include/c++/4.8/fstream:72:11: note: ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8/ios:43:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:27:0,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/usr/include/c++/4.8/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33:0,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/home/ubuntu/denovogear/src/lib/../include/dng/io/file.h: In member function ‘dng::io::File& dng::io::File::operator=(dng::io::File&&)’:
/home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:115:11: error: use of deleted function ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’
     file_ = std::move(other.file_);
           ^
In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:27:0,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/usr/include/c++/4.8/fstream:776:11: note: ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:776:11: error: use of deleted function ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.8/iterator:65:0,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/istream:795:11: note: ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.8/istream:795:11: error: use of deleted function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’
/usr/include/c++/4.8/istream:58:11: note: ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8/istream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8/ios:42:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/bits/ios_base.h:795:5: error: ‘std::ios_base& std::ios_base::operator=(const std::ios_base&)’ is private
     operator=(const ios_base&);
     ^
In file included from /usr/include/c++/4.8/ios:44:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8/iterator:65:0,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/istream:795:11: error: use of deleted function ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’
     class basic_iostream
           ^
In file included from /usr/include/c++/4.8/iterator:64:0,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/ostream:58:11: note: ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:27:0,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/usr/include/c++/4.8/fstream:776:11: error: use of deleted function ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:72:11: note: ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8/ios:43:0,
                 from /usr/include/c++/4.8/ostream:38,
                 from /usr/include/c++/4.8/iterator:64,
                 from /usr/include/boost/detail/iterator.hpp:54,
                 from /usr/include/boost/array.hpp:48,
                 from /usr/include/boost/multi_array/range_list.hpp:19,
                 from /usr/include/boost/multi_array/extent_gen.hpp:17,
                 from /usr/include/boost/multi_array/base.hpp:22,
                 from /usr/include/boost/multi_array.hpp:21,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/depths.h:28,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:20:
/usr/include/c++/4.8/streambuf:810:7: error: ‘std::basic_streambuf<_CharT, _Traits>& std::basic_streambuf<_CharT, _Traits>::operator=(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       operator=(const basic_streambuf&) { return *this; };
       ^
In file included from /home/ubuntu/denovogear/src/lib/../include/dng/io/file.h:27:0,
                 from /home/ubuntu/denovogear/src/lib/../include/dng/io/ad.h:33,
                 from /home/ubuntu/denovogear/src/lib/ad.cc:22:
/usr/include/c++/4.8/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
make[2]: *** [src/lib/CMakeFiles/libdng.dir/ad.cc.o] Error 1
make[1]: *** [src/lib/CMakeFiles/libdng.dir/all] Error 2
make: *** [all] Error 2`

**Comment by reedacartwright** [comment]
@jgarc111, does https://github.com/reedacartwright/denovogear/tree/bugfix/MovingFstream solve the issue?

**Comment by jgarciamesa** [comment]
@reedacartwright, unfortunately it doesn't. More accurate information about the compiler failure might be found [here](https://circleci.com/gh/bioconda/bioconda-recipes/6904?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build).

**Comment by reedacartwright** [comment]
I made some more changes to the branch. So please try it again.

--
Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute
Arizona State University
==================
Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign B-220C, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by jgarciamesa** [comment]
It compiled successfully (with gcc 4.8.4 and boost 1.64.0).

**Comment by zhangjianruwang** [comment]
so how long is it before we can use conda to install denovogear-develop version?

**Comment by jgarciamesa** [comment]
We are on the process of updating the bioconda recipe for denovogear and I expect it to be done soon. As soon as it's available I will let you know.

**Comment by reedacartwright** [comment]
The fix has been merged with the develop branch.

**Comment by reedacartwright** [comment]
@jgarc111, has the bioconda recipe been updated?

**Comment by jgarciamesa** [comment]
After some time I recently got feedback from an issue I opened at the bioconda github repository and I'm working on the recipe update.

**Comment by jgarciamesa** [comment]
@reedacartwright , as of right now the recipe update will contain commit id 16e960e11cdde506b46dac0255430814ad0c7aea . Do you want to use a more recent one?

**Comment by reedacartwright** [comment]
Yes, do the one after my pedng pull request is merged.

--
Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute
Arizona State University
==================
Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign B-220C, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by jgarciamesa** [comment]
Recipe updated with commit id 3ae70ba8272ca4d6aa96bdb41170ce0739a5aa4a . All tests passed and pull request on bioconda/bioconda-recipes should be merged soon.
